/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simplehotelmanagementsystem;

import javax.swing.JOptionPane;
import database.connectDB;
import java.awt.Cursor;
import java.sql.*;
import java.util.ArrayList;

/**
 *
 * @author root
 */
public class AvalableRoom extends javax.swing.JFrame {
     connectDB dbconn = new connectDB();
    /**
     * Creates new form AvalableRoom
     */
    public AvalableRoom() {
       dbconn.connect();
       
        initComponents();
        
       roomVisibility();
      
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Dpanal = new javax.swing.JDesktopPane();
        noofperl = new javax.swing.JLabel();
        condition = new javax.swing.JComboBox<>();
        acnonl = new javax.swing.JLabel();
        check = new javax.swing.JLabel();
        checkbtn = new javax.swing.JButton();
        type = new javax.swing.JComboBox<>();
        RoomPanal = new javax.swing.JPanel();
        Room11 = new javax.swing.JButton();
        Room1 = new javax.swing.JButton();
        Room12 = new javax.swing.JButton();
        Room6 = new javax.swing.JButton();
        Room7 = new javax.swing.JButton();
        Room8 = new javax.swing.JButton();
        Room9 = new javax.swing.JButton();
        Room10 = new javax.swing.JButton();
        Room4 = new javax.swing.JButton();
        Room13 = new javax.swing.JButton();
        Room5 = new javax.swing.JButton();
        Room14 = new javax.swing.JButton();
        Room3 = new javax.swing.JButton();
        Room15 = new javax.swing.JButton();
        Room2 = new javax.swing.JButton();
        close = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        noofperl.setText("Couple or Family");

        condition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "NON-AC" }));

        acnonl.setText("AC or NON-AC");

        check.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        check.setText("Check Avalable Rooms");

        checkbtn.setText("check");
        checkbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbtnActionPerformed(evt);
            }
        });

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Couple", "Family" }));

        Room11.setText("11");
        Room11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room11ActionPerformed(evt);
            }
        });

        Room1.setText("01");
        Room1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room1ActionPerformed(evt);
            }
        });

        Room12.setText("12");
        Room12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room12ActionPerformed(evt);
            }
        });

        Room6.setText("06");
        Room6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room6ActionPerformed(evt);
            }
        });

        Room7.setText("07");
        Room7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room7ActionPerformed(evt);
            }
        });

        Room8.setText("08");
        Room8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room8ActionPerformed(evt);
            }
        });

        Room9.setText("09");
        Room9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room9ActionPerformed(evt);
            }
        });

        Room10.setText("10");
        Room10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room10ActionPerformed(evt);
            }
        });

        Room4.setText("04");
        Room4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room4ActionPerformed(evt);
            }
        });

        Room13.setText("13");
        Room13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room13ActionPerformed(evt);
            }
        });

        Room5.setText("05");
        Room5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room5ActionPerformed(evt);
            }
        });

        Room14.setText("14");
        Room14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room14ActionPerformed(evt);
            }
        });

        Room3.setText("03");
        Room3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room3ActionPerformed(evt);
            }
        });

        Room15.setText("15");
        Room15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room15ActionPerformed(evt);
            }
        });

        Room2.setText("02");
        Room2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RoomPanalLayout = new javax.swing.GroupLayout(RoomPanal);
        RoomPanal.setLayout(RoomPanalLayout);
        RoomPanalLayout.setHorizontalGroup(
            RoomPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoomPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RoomPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RoomPanalLayout.createSequentialGroup()
                        .addComponent(Room11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room12))
                    .addGroup(RoomPanalLayout.createSequentialGroup()
                        .addGroup(RoomPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Room1)
                            .addComponent(Room6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RoomPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Room7)
                            .addComponent(Room2))))
                .addGap(6, 6, 6)
                .addGroup(RoomPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RoomPanalLayout.createSequentialGroup()
                        .addComponent(Room13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room15))
                    .addGroup(RoomPanalLayout.createSequentialGroup()
                        .addComponent(Room8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room10))
                    .addGroup(RoomPanalLayout.createSequentialGroup()
                        .addComponent(Room3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RoomPanalLayout.setVerticalGroup(
            RoomPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(RoomPanalLayout.createSequentialGroup()
                .addGroup(RoomPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Room4)
                    .addComponent(Room5)
                    .addComponent(Room3)
                    .addComponent(Room2)
                    .addComponent(Room1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RoomPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Room8)
                    .addComponent(Room9)
                    .addComponent(Room10)
                    .addComponent(Room7)
                    .addComponent(Room6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RoomPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Room14)
                    .addComponent(Room13)
                    .addComponent(Room15)
                    .addComponent(Room12)
                    .addComponent(Room11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        Dpanal.setLayer(noofperl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dpanal.setLayer(condition, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dpanal.setLayer(acnonl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dpanal.setLayer(check, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dpanal.setLayer(checkbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dpanal.setLayer(type, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dpanal.setLayer(RoomPanal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Dpanal.setLayer(close, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DpanalLayout = new javax.swing.GroupLayout(Dpanal);
        Dpanal.setLayout(DpanalLayout);
        DpanalLayout.setHorizontalGroup(
            DpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DpanalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(check)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(DpanalLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(DpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DpanalLayout.createSequentialGroup()
                        .addGroup(DpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DpanalLayout.createSequentialGroup()
                                .addComponent(acnonl)
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DpanalLayout.createSequentialGroup()
                                .addComponent(noofperl)
                                .addGap(18, 18, 18)))
                        .addGroup(DpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(condition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkbtn))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(DpanalLayout.createSequentialGroup()
                        .addComponent(RoomPanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(close)))
                .addContainerGap())
        );
        DpanalLayout.setVerticalGroup(
            DpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DpanalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(check)
                .addGap(18, 18, 18)
                .addGroup(DpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acnonl)
                    .addComponent(condition, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noofperl)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RoomPanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DpanalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(close)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dpanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dpanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbtnActionPerformed
           String typ = type.getSelectedItem().toString();//get user selected values
           String cond = condition.getSelectedItem().toString();
           int typValue=2,condValue=2;
           if(typ.equals("Couple")){//if type is couple set 1 to typValue else type is family set 0 to typValue 
               typValue = 1;
           }else if(typ.equals("Family")){
               typValue = 0; 
           }
           if(cond.equals("AC")){//if room is ac then set 1 to condValue else room is non-ac set 0 to condValue
               condValue = 1;
           }else if(cond.equals("NON-AC")){
               condValue = 0;
           }
           
        try{
         
           String sql = "SELECT id FROM rooms WHERE (NOT EXISTS (SELECT room_id FROM booking WHERE rooms.id = booking.room_id) ) AND ac_or_non=? AND type=?;";//sql query
           
           PreparedStatement statement = dbconn.conn.prepareStatement(sql);//prepare query statement for db connection
           statement.setInt(1,condValue);//complete statement
           statement.setInt(2,typValue);           
           ResultSet     result = statement.executeQuery();//execute query and get result
           
           if(result != null){
           for(int i = 0;result.next(); i++){
              int id = result.getInt("id");
              //System.out.println(id);
              switch(id){//room is avalable them set buttom visible 
                  case 1:Room1.setVisible(true);break;
                  case 2:Room2.setVisible(true);break;
                  case 3:Room3.setVisible(true);break;
                  case 4:Room4.setVisible(true);break;
                  case 5:Room5.setVisible(true);break;
                  case 6:Room6.setVisible(true);break;
                  case 7:Room7.setVisible(true);break;
                  case 8:Room8.setVisible(true);break;
                  case 9:Room9.setVisible(true);break;
                  case 10:Room10.setVisible(true);break;
                  case 11:Room11.setVisible(true);break;
                  case 12:Room12.setVisible(true);break;
                  case 13:Room13.setVisible(true);break;
                  case 14:Room14.setVisible(true);break;
                  case 15:Room15.setVisible(true);break;
                  default: JOptionPane.showMessageDialog(null, "There is no rooms"); break;
              }
                          
            }
           
         
           }else if(result == null){
               JOptionPane.showMessageDialog(null,"There is no rooms");//result null there is no rooms
           }
           
       }catch(Exception ex){
           JOptionPane.showMessageDialog(null, "Exception");
       }
       
    }//GEN-LAST:event_checkbtnActionPerformed

    private void Room9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room9ActionPerformed
          
        bookRoom booking = new bookRoom();
        booking.getid(9);
        booking.setVisible(true);
        dispose();
    }//GEN-LAST:event_Room9ActionPerformed

    
    private void Room7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room7ActionPerformed
          
        bookRoom booking = new bookRoom();
        booking.getid(7);
        booking.setVisible(true);
        dispose();
    }//GEN-LAST:event_Room7ActionPerformed

    private void Room1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room1ActionPerformed
        
        bookRoom booking = new bookRoom();
        booking.getid(1);
        booking.setVisible(true);
        dispose();
    }//GEN-LAST:event_Room1ActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        Receptionist reception = new Receptionist();
        reception.setVisible(true);//close current window and open reseptionist home page
        dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void Room2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room2ActionPerformed
         
        bookRoom booking = new bookRoom();
        booking.getid(2);
        booking.setVisible(true);
        dispose();
    }//GEN-LAST:event_Room2ActionPerformed

    private void Room4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room4ActionPerformed
          
        bookRoom booking = new bookRoom();
        booking.getid(4);
        booking.setVisible(true);
        dispose();
    }//GEN-LAST:event_Room4ActionPerformed

    private void Room3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room3ActionPerformed
          
        bookRoom booking = new bookRoom();
        booking.getid(3);
        booking.setVisible(true);
        dispose();
    }//GEN-LAST:event_Room3ActionPerformed

    private void Room5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room5ActionPerformed
          
        bookRoom booking = new bookRoom();
        booking.getid(5);
        booking.setVisible(true);
        dispose();
    }//GEN-LAST:event_Room5ActionPerformed

    private void Room6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room6ActionPerformed
          
        bookRoom booking = new bookRoom();
        booking.getid(6);
        booking.setVisible(true);
        dispose();
    }//GEN-LAST:event_Room6ActionPerformed

    private void Room8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room8ActionPerformed
          
        bookRoom booking = new bookRoom();
        booking.getid(8);
        booking.setVisible(true);
        dispose();
    }//GEN-LAST:event_Room8ActionPerformed

    private void Room10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room10ActionPerformed
          
        bookRoom booking = new bookRoom();
        booking.getid(10);
        booking.setVisible(true);
        dispose();
    }//GEN-LAST:event_Room10ActionPerformed

    private void Room11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room11ActionPerformed
          
        bookRoom booking = new bookRoom();
        booking.getid(11);
        booking.setVisible(true);
        dispose();
    }//GEN-LAST:event_Room11ActionPerformed

    private void Room12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room12ActionPerformed
         
        bookRoom booking = new bookRoom();
        booking.getid(12);
        booking.setVisible(true);
        dispose();
    }//GEN-LAST:event_Room12ActionPerformed

    private void Room13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room13ActionPerformed
          
        bookRoom booking = new bookRoom();
        booking.getid(13);
        booking.setVisible(true);
        dispose();
    }//GEN-LAST:event_Room13ActionPerformed

    private void Room14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room14ActionPerformed
          
        bookRoom booking = new bookRoom();
        booking.getid(14);
        booking.setVisible(true);
        dispose();
    }//GEN-LAST:event_Room14ActionPerformed

    private void Room15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room15ActionPerformed
          
        bookRoom booking = new bookRoom();
        booking.getid(15);
        booking.setVisible(true);
        dispose();
    }//GEN-LAST:event_Room15ActionPerformed
    private void roomVisibility(){
            Room1.setVisible(false);
            Room2.setVisible(false);
            Room3.setVisible(false);
            Room4.setVisible(false);
            Room5.setVisible(false);
            Room6.setVisible(false);
            Room7.setVisible(false);
            Room8.setVisible(false);
            Room9.setVisible(false);
            Room10.setVisible(false);
            Room11.setVisible(false);
            Room12.setVisible(false);
            Room13.setVisible(false);
            Room14.setVisible(false);
            Room15.setVisible(false);
            Dpanal.setVisible(true);
            RoomPanal.setVisible(true);
            Room1.setCursor(Dpanal.getCursor());
            
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvalableRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvalableRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvalableRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvalableRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvalableRoom().setVisible(true);
                
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Dpanal;
    private javax.swing.JButton Room1;
    private javax.swing.JButton Room10;
    private javax.swing.JButton Room11;
    private javax.swing.JButton Room12;
    private javax.swing.JButton Room13;
    private javax.swing.JButton Room14;
    private javax.swing.JButton Room15;
    private javax.swing.JButton Room2;
    private javax.swing.JButton Room3;
    private javax.swing.JButton Room4;
    private javax.swing.JButton Room5;
    private javax.swing.JButton Room6;
    private javax.swing.JButton Room7;
    private javax.swing.JButton Room8;
    private javax.swing.JButton Room9;
    private javax.swing.JPanel RoomPanal;
    private javax.swing.JLabel acnonl;
    private javax.swing.JLabel check;
    private javax.swing.JButton checkbtn;
    private javax.swing.JButton close;
    private javax.swing.JComboBox<String> condition;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel noofperl;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
